# Generated by Django 5.0.1 on 2024-01-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('main', '0002_videocontent_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_videos',
            field=models.ManyToManyField(to='main.videocontent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_videos',
            field=models.ManyToManyField(related_name='user_liked_videos', to='main.videocontent'),
        ),
    ]
