# Generated by Django 5.0.1 on 2024-01-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_videocontent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
